### ISSUE TITLE
Issues with the email input in intro

### ISSUE THREAD

**Issue by letsintegreat** [harshagrawal523/Portfolyser#17]
Right now the user can edit the `email` input in `/intro`. Therefore, any user can add intro for some other user if they know their email, which obviously should not happen.
But also, we cannot make `email` input uneditable, because one might want to add another email in the portfolio.

To resolve this issue, make another property in `user.js`, let's say `portfolio_email`.
When POST request is made at `/intro`,  set the value of `email` as the email of the logged-in user, and put the email entered by the user in the form in `portfolio_email`

Make appropriate changes in `final.ejs` too.

**Comment by harshagrawal523** [comment]
> 

Yes even I had this in mind , but what I was thinking was if there is a way to make dynamic fields so one can add as many emails as they want. But having the current email is must because emails are unique and with the help of that only we are looking for his intro from database which has of all the users.
